### ISSUE TITLE
Program works well with rebranded huion tablets and could likely work with others as well

### ISSUE THREAD

**Issue by MacrosV** [jcbastosportela/HuionScreenSelector#1]
Good afternoon,

I just wanted to open an issue request to thank you for writing and sharing this utility and let you know that it also works rather well with rebranded tablets such as the monoprice 10594 which I believe is just a rebranded Huion H610, however I did have to modify line 67 of the inputs.py file to contain the string "10594" instead of "huion". I imagine it would not be too difficult to get this utility to support more than just huion tablets if you had it prompt the user for a device string if the device is not found and then ask the user to verify that it works, in which case the value entered could be written to disk so as to allow for persistence. Thanks again!

**Comment by jcbastosportela** [comment]
Hi @MacrosV you would be more than welcome to submit a pull request with your suggestion :). If you don't have the knowledge or time let me know and I will try to pick it up when I have availability (even then I will probably need your support for testing it).

**Comment by MacrosV** [comment]
I will do give it a go, I have some experience with python, but am still fairly new to it so my solution may not end up using all best practices, but I will let you be the judge of that, thanks!

**Comment by jcbastosportela** [comment]
@MacrosV meanwhile I made some changes, but maybe not exactly what you had in mind. I have disabled the default hard-coded filter for `huion` on the devices listed by xinput; with this changes by default all the input devices will be added to the list of devices (this can be annoying specially when you have many input devices). For addressing this last nuance I have added support for input arguments so a 'filter' can be passed as argument.

Could you try the code on the branch https://github.com/jcbastosportela/HuionScreenSelector/tree/support_additional_devices ?

In your case you could run like:
`HuionScreenSelector -d 10594`

If you still feel like adding the support for user prompt instead, please go ahead and make a pull request to this repo. :+1: 

If you confirm that the changes above suits you I will merge it into master.

**Comment by MacrosV** [comment]
I just tested it and it works rather well if I start it using the line you suggested. I was just going to make a new file called something like "devicelist.csv" and then just have a function at the beginning load up the entries from it into a list saved as a variable such as "devicelist". Then I was planning on modifying the hardcoded function so that it would just see if anything matched using in. Initially I had thought about adding a prompt that would say something like "device not found, please enter identifier or press q to quit" and then append the output into the devicelist.csv file, but I am not sure it is entirely necessary. I think I will still try and make some changes then let you know, but the above change works well for me right now, thanks!

**Comment by jcbastosportela** [comment]
> I was just going to make a new file called something like "devicelist.csv" and then just have a function at the beginning load up the entries from it into a list saved as a variable such as "devicelist".

It is a nice idea to have a file with settings :smiley: but if you go that path, maybe instead of a .csv it could be used some ready configuration support package (like https://docs.python.org/3/library/configparser.html) or at least .JSON file format, as this allows for a hierarchical and object oriented storage of info.

 

> Initially I had thought about adding a prompt that would say something like "device not found, please enter identifier or press q to quit"

Well, about this, having this prompt to show when the HuionScreenSelector is run can be an issue for some usages, for example mine :rofl:  because I don't manually run the program, I have created a service that runs at startup and starts it. In this case that prompt would be lost. Maybe here on the sys tray menu "Huion devices" an entry saying "no device matching found", and a click on in could bring a input window for taking the "device name"
